name: ms2kiresnet_env
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=10.1.243
  - matplotlib=3.1.3
  - numpy=1.18.1
  - opencv=3.4.2
  - pip=20.0.2
  - python=3.7.7
  - pytorch=1.4.0
  - scikit-learn=0.22.1
  - scipy=1.4.1
  - pip:
    - pytorch-ranger==0.1.1
    - spectral==0.20
    - torch-optimizer==0.0.1a12
    - torch-summary==1.2.0

